apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-manager
  labels:
    app: api-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-manager
  template:
    metadata:
      labels:
        app: api-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: api-manager
          image: api-manager-image
          command:
            - '/app/api-manager'
          args:
            # - '-prom_endpoint'
            # - '/metrics'
            # - '-prom_listen_addr'
            # - ':2112'
            - '-dsn'
            - 'bin-manager:398e02d8-8aaa-11ea-b1f6-9b65a2a4f3a3@tcp(10.126.80.5:3306)/bin_manager'
            - '-rabbit_addr'
            - 'amqp://guest:guest@rabbitmq.voipbin.net:5672'
            - '-rabbit_exchange_delay'
            - 'bin-manager.delay'
            - '-rabbit_queue_call'
            - 'bin-manager.call-manager.request'
            - '-rabbit_queue_flow'
            - 'bin-manager.flow-manager.request'
            - '-redis_addr'
            - '10.164.15.220:6379'
            - '-redis_db'
            - '1'
            - '-jwt_key'
            - 'voipbin'
            - '-ssl_private'
            - './etc/ssl/privkey.pem'
            - '-ssl_cert'
            - './etc/ssl/cert.pem'

          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
            - name: service
              protocol: "TCP"
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /ping
              port: 443
              scheme: HTTPS
          resources:
            limits:
              cpu: "50m"
              memory: "20M"
