apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: []

resources:
  - namespace.yml
  - deployment.yml

images:
  - name: rag-manager-image
    newName: rag-manager
    newTag: latest
